# This is a basic workflow to help you get started with Actions

name: Dev Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  deploy:
    # The type of runner that the job will run on
    runs-on: dev
    # needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install Modules & Build
        run: |
          # cd /var/www/sourcefy_frontend/
          npm install --force
          # export REACT_APP_NODE_ENV=production
          # npm run build

      # Runs a set of commands using the runners shell
      - name: Move files to deployment folder
        run: cp -r ./* /var/www/sourcefy_frontend/
      
